version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env.development
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

  test:
    container_name: api-test
    restart: always
    build:
      context: ..
      dockerfile: ./test.Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./.env.test
    environment:
      - NODE_ENV=test
    networks:
      - mynetwork

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynetwork

volumes: 
 data: {}

networks:
  mynetwork:
    driver: bridge
